<?php
require_once '../config/db.php';
require_once '../includes/auth.php';
requireAdmin();
$success=flash('booking_admin_success');
$search = cleanInput($_GET['search'] ?? '');
$status = cleanInput($_GET['status'] ?? '');
$params=[]; $where=[];
if($search!==''){ $where[]='(u.username LIKE :search OR u.email LIKE :search OR c.name LIKE :search)'; $params['search']="%$search%"; }
if($status!==''){ $where[]='b.status = :status'; $params['status']=$status; }
$sql='SELECT b.*, u.username, u.email, u.id AS user_id, c.name AS car_name FROM bookings b JOIN users u ON b.user_id=u.id JOIN cars c ON b.car_id=c.id'.($where?' WHERE '.implode(' AND ',$where):'').' ORDER BY b.created_at DESC';
$stmt=$pdo->prepare($sql); $stmt->execute($params); $bookings=$stmt->fetchAll();
?>
<html><head><link rel="stylesheet" href="../css/all.min.css"><link rel="stylesheet" href="../css/bootstrap.min.css"><link rel="stylesheet" href="../css/style.css"><title>Manage Bookings - Furni</title></head><body><?php include '_admin_nav.php'; ?>
<section class="bg-main py-5"><div class="container py-4"><div class="card shadow border-0 rounded-4"><div class="card-body"><h3 class="mb-4">Manage Bookings</h3><?php if($success): ?><div class="alert alert-success"><?php echo e($success); ?></div><?php endif; ?>
<form class="row g-3 mb-4" method="GET"><div class="col-md-6"><input class="form-control" name="search" placeholder="Search user, email, or car" value="<?php echo e($search); ?>"></div><div class="col-md-4"><select class="form-select" name="status"><option value="">All Status</option><?php foreach(['pending','confirmed','cancelled','completed'] as $s): ?><option value="<?php echo $s; ?>" <?php echo $status===$s?'selected':''; ?>><?php echo ucfirst($s); ?></option><?php endforeach; ?></select></div><div class="col-md-2"><button class="btn btn-dark w-100">Filter</button></div></form>
<div class="table-responsive"><table class="table table-striped align-middle"><thead class="table-dark"><tr><th>ID</th><th>User</th><th>Car</th><th>Pickup</th><th>Return</th><th>Days</th><th>Total</th><th>Status</th><th>Notes</th><th>Update</th></tr></thead><tbody>
<?php foreach($bookings as $b): ?><tr><td><?php echo (int)$b['id']; ?></td><td><a href="user_details.php?id=<?php echo (int)$b['user_id']; ?>"><?php echo e($b['username']); ?></a><br><small><?php echo e($b['email']); ?></small></td><td><?php echo e($b['car_name']); ?></td><td><?php echo e($b['pickup_date']); ?></td><td><?php echo e($b['return_date']); ?></td><td><?php echo (int)$b['total_days']; ?></td><td>$<?php echo number_format((float)$b['total_price'],2); ?></td><td><?php echo e($b['status']); ?><br><small><?php echo e($b['status_reason'] ?? ''); ?></small></td><td style="min-width:220px"><small>User: <?php echo e($b['user_note'] ?? ''); ?></small><br><small>Admin: <?php echo e($b['admin_notes'] ?? ''); ?></small></td><td style="min-width:360px"><form method="POST" action="update_booking.php" class="row g-2"><?php echo csrfField(); ?><input type="hidden" name="id" value="<?php echo (int)$b['id']; ?>"><div class="col-md-4"><select name="status" class="form-select form-select-sm"><?php foreach(['pending','confirmed','cancelled','completed'] as $s): ?><option value="<?php echo $s; ?>" <?php echo $b['status']===$s?'selected':''; ?>><?php echo ucfirst($s); ?></option><?php endforeach; ?></select></div><div class="col-md-4"><input class="form-control form-control-sm" name="status_reason" placeholder="Reason" value="<?php echo e($b['status_reason'] ?? ''); ?>"></div><div class="col-md-3"><input class="form-control form-control-sm" name="admin_notes" placeholder="Notes" value="<?php echo e($b['admin_notes'] ?? ''); ?>"></div><div class="col-md-1"><button class="btn btn-sm btn-dark">Save</button></div></form></td></tr><?php endforeach; ?><?php if(!$bookings): ?><tr><td colspan="10" class="text-center">No bookings found.</td></tr><?php endif; ?>
</tbody></table></div></div></div></div></section><script src="../js/bootstrap.bundle.min.js"></script></body></html>
